<?php

namespace App\Http\Requests\Students;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StudentEnrollMassiveRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {

        return [
            'courses' =>[
                'required',
                'array',
            ],
            'courses.*' => [
                'required',
                'integer',
                Rule::exists('courses', 'id')->whereNull('deleted_at')
            ],
        ];
    }

    public function messages()
    {
        $message =  parent::messages(); // TODO: Change the autogenerated stub
        $message['courses.*.exists'] = 'The selected course is invalid';
        return $message;
    }
}
