<?php

namespace App\Http\Requests\Students;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StudentEnrollRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {

        $student_id = $this->route('student');
        return [
            'course_id' => [
                'required',
                Rule::exists('courses', 'id')->whereNull('deleted_at'),
                Rule::unique('course_students', 'course_id')->where('student_id', $student_id)
            ],
        ];
    }

    public function messages()
    {
        $message = parent::messages(); // TODO: Change the autogenerated stub
        $newMessages = [
            'course_id.unique' => 'The student is already enrolled in this course',
        ];
        return array_merge($message, $newMessages);
    }
}
